### ISSUE TITLE
No fuel on board and climb rate

### ISSUE THREAD

**Issue by Arcodacalheta** [headwind-msfs/a330-900#1]
I attempted a flight from KORD to LSZH today that ended with no fuel on board before reaching my cruise altitude. I loaded my fuel from the ATSU page and verified on the EFB fuel page that it was correctly loaded (I had 58 tons). When reaching 33000 feet my tanks were empty. the quantity in tank was correctly input in MCDU (INIT page and ATSU) and EFB.
Another issue I had was with the climb speed, on three occasions, my speed was exceeding the upper limit although my climb rate was normal for the altitude. I let it manage by itself and each time it would slowly go down to the set speed.
I thank you for your work and efforts to bring us a fair rendition of this beautiful airplane.

**Comment by Revyn112** [comment]
Please check again with the latest version.
