### ISSUE TITLE
Broken ND

### ISSUE THREAD

**Issue by relubwu** [headwind-msfs/a330-900#11]
The ND is broken after some tinkering with the flight plan: 

![nd](https://i.imgur.com/9zGLnsl.png)

How to reproduce: 

- Create a flight plan
- Do a few temporary insertions (like selecting SID/STARs but not inserting them)
- The captain's side ND is broken, planned route is no longer drawn.

**Comment by SimonJeanneteau** [comment]
Do you know if this is due to the new version, seems to work great before ?

**Comment by SimonJeanneteau** [comment]
Bug already in the fbw 0.7.x, apply utf-8 patch to be able to up sim speed without problems.

**Comment by Revyn112** [comment]
@relubwu please try this: https://docs.flybywiresim.com/fbw-a32nx/support/reported-issues/?h=utf8#unable-to-taxi-aircraft-does-not-move

**Comment by xhemp** [comment]
I've seen this happening as well and the UTF-8 issue above didn't help, unfortunately.

**Comment by Revyn112** [comment]
> I've seen this happening as well and the UTF-8 issue above didn't help, unfortunately. 

Can you test again with this build and report back? https://github.com/headwind-msfs/a330-900/releases/download/vmain/full.zip

Please remove everything related to previous versions, also included in Microsoft Flight Simulator %appdata%.

**Comment by xhemp** [comment]
I think deleting any headwind-a330-900 %appdata% for MSFS did the trick (although by doing this I had to recalibrate my throttle controllers), @Revyn112. Maybe this should go to the FAQ?

**Comment by Revyn112** [comment]
as this issue got solved i close this issue.
