### ISSUE TITLE
COM2 Radio is inoperative.

### ISSUE THREAD

**Issue by guillermosnipe** [headwind-msfs/a330-900#2]
COM2 Radio is not operative, it doesn't even show a proper frequency. This issue also replicates to vPilot when flying online. See attached screenshots.

<img width="548" alt="image" src="https://user-images.githubusercontent.com/14862173/145883556-f30d2530-e8eb-466f-9f1c-a8aa6129c938.png">

How to reproduce it:
- Load the plane
- Try to tune some freq of your choice using COM2

**Comment by Revyn112** [comment]
Please check with the latest version and report back if the issue still persists.
