### ISSUE TITLE
Aircraft Loading Problem.

### ISSUE THREAD

**Issue by KoplaNum** [headwind-msfs/a330-900#24]
I am trying to load the aircraft with max fuel and max weight but it is not possible. If you look at the weight I am getting -478
![ErrorWeight](https://user-images.githubusercontent.com/77222925/164891205-acd57732-8dc1-4e25-96e7-f6e48b17effa.jpg)

**Comment by Revyn112** [comment]
This is because FBW simulate the loading phases in the MCDU when passenger loading start. As the plane is initial loaded the pax and cargo is set to null.
