### ISSUE TITLE
VNAV Issues. NEXT WAYPOINT feature in the Vertical Rev Page doesn't work as expected.

### ISSUE THREAD

**Issue by guillermosnipe** [headwind-msfs/a330-900#3]
**How to reproduce it:**
- Open the F-PLN page.
- Select a Waypoint and go to the Vertical Revision page.
- Type a waypoint that is located after the current one.

**Expected result:**
- You should see the tmpy changed FPL reflecting the new wpt insertion after the wpt of your choice.

**Current result:**
- You see the tmpy changed FPL displaying the new entry point before and not after the desired waypoint.

**Comment by Revyn112** [comment]
Please check with the latest version and report back if the issue still persists.
