### ISSUE TITLE
FBW Integration issues - Fuel amount loaded through the FMGC is incorrect.

### ISSUE THREAD

**Issue by guillermosnipe** [headwind-msfs/a330-900#4]
**How to reproduce it:**

- Fill a FP using simbrief.
- Proceed to init your FMGC using simbrief's data.
- Load the fuel using the FMGC

**Expected result:**
- It loads the BLOCK fuel calculated for the flight that matches the simbrief's OFP.

**Current result:**
- It seems to load the TRIP fuel calculated for the flight, which results in incorrect Fuel Planning and prediction values, leading to negative results.

**Comment by Revyn112** [comment]
Please check with the latest version and report back if the issue still persists.
